name: Publish package to GitHub Packages

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Begin CI...
        uses: actions/checkout@v3

      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          registry-url: "https://npm.pkg.github.com"

      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version-file: .node-version

      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v3
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Change version
        run: $(npm bin)/changeset version

      - name: Create Pull Request
        id: cpr
        if: github.event.inputs.npmDistTag == 'latest'
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.BOT_TOKEN }}
          commit-message: 'chore(deps): update engines to ${{ github.event.inputs.version }}'
          committer: 'Prismo <prismabots@gmail.com>'
          author: 'Prismo <prismabots@gmail.com>'
          branch: deps/engines-${{ github.event.inputs.version }}
          delete-branch: true
          labels: automerge
          title: 'chore(deps): update engines to ${{ github.event.inputs.version }}'
          body: |
            This automatic PR updates the engines to version `${{ github.event.inputs.version }}`. This will get automatically merged if all the tests pass.
            ## Packages
            | Package | NPM URL |
            |---------|---------|
            |`@prisma/engines-version`| https://npmjs.com/package/@prisma/engines-version/v/${{ github.event.inputs.version }}|
            |`@prisma/prisma-fmt-wasm`| https://npmjs.com/package/@prisma/prisma-fmt-wasm/v/${{ github.event.inputs.version }}|
            ## Engines commit
            [`prisma/prisma-engines@${{ steps.extract-engine-commit-hash.outputs.hash }}`](https://github.com/prisma/prisma-engines/commit/${{ steps.extract-engine-commit-hash.outputs.hash }})
